### ISSUE TITLE
[PROPOSAL] 添加cli选项以避免用户输入密码明文

### ISSUE THREAD

**Issue by glyh** [ykxVK8yL5L/pikpak-fuse#1]
RT, 可以参见git push的ssh密钥，nmcli 的-a选项等等。

**Comment by ykxVK8yL5L** [comment]
> 

感谢建议 我考虑下怎么实现 密码保存的话 主要是用于提交给服务器验证如果做了加密的话  还需要解密后再提交  如果程序可以加密解密的话 技术人员同样可以解密保存的密码  由于是本地保存倒不担心泄漏问题 而且不会有人在pikpak里存重要文件吧？ 感觉泄漏了也没啥事😂

**Comment by glyh** [comment]
emm我没说要保存密码，只是说最好避免密码明文输入

**Comment by ykxVK8yL5L** [comment]
> emm我没说要保存密码，只是说最好避免密码明文输入

明白 可是pikpak服务器验证需要的是未加密的用户名和密码  要么像aliyun一样用refresh_token  个人使用中aliyun经常莫名其妙停止 所以没有用这种方法   你这个问题面向的对象是哪种等级的？ 编程大神还是小白用户？

**Comment by ykxVK8yL5L** [comment]
> emm我没说要保存密码，只是说最好避免密码明文输入

用户名密码写到配置文件里可以么？

**Comment by glyh** [comment]
大概这种的：
```python
#!/usr/bin/env python
import getpass
password = getpass.getpass()
print(password)
```
用户输入的密码没有办法被看到或者保存在命令行history里就行了

**Comment by ykxVK8yL5L** [comment]
> 

这个是不用保存了 但是需要每次输入 就麻烦了吧

**Comment by glyh** [comment]
好吧，有道理。closed.
