### ISSUE TITLE
Error: initialize pikpakDrive client failed

### ISSUE THREAD

**Issue by Hesidv** [ykxVK8yL5L/pikpak-fuse#2]
![snipaste_2022-07-25](https://user-images.githubusercontent.com/38974294/180805246-0192ec20-23e9-48ce-b47d-4581fa9afb06.jpg)

**Comment by ykxVK8yL5L** [comment]
> ![snipaste_2022-07-25](https://user-images.githubusercontent.com/38974294/180805246-0192ec20-23e9-48ce-b47d-4581fa9afb06.jpg)

请打开调试模式   需要更多信息  最好进群反馈下   可以看下视频里的tg链接
