### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/drive/mod.rs:244:36 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by Hesidv** [ykxVK8yL5L/pikpak-fuse#3]
![image_2](https://user-images.githubusercontent.com/38974294/180821000-6e194f97-ebe9-48d1-9184-084371d7936a.png)

**Comment by glyh** [comment]
The same here

**Comment by ykxVK8yL5L** [comment]
> ![image_2](https://user-images.githubusercontent.com/38974294/180821000-6e194f97-ebe9-48d1-9184-084371d7936a.png)

问题没有提醒导致没看到😂 出现这种问题大部分是登录问题 需要用邮箱和密码的方式登录 如果是谷歌登录需要后台绑定邮箱并设置密码

**Comment by ZHLONG321** [comment]
Same problem with email login

**Comment by ykxVK8yL5L** [comment]
> Same problem with email login

If you are using gmail to login. You need set password in pikpak.

**Comment by ZHLONG321** [comment]
> > Same problem with email login
> 
> If you are using gmail to login. You need set password in pikpak.

No, I use microsoft devloper email "xxxxx@xxx.onmicrosoft.com" and password have set. I can login by pikpakAPI (https://github.com/Quan666/PikPakAPI)

**Comment by ykxVK8yL5L** [comment]
> > > Same problem with email login
> > 
> > 
> > If you are using gmail to login. You need set password in pikpak.
> 
> No, I use microsoft devloper email "[xxxxx@xxx.onmicrosoft.com](mailto:xxxxx@xxx.onmicrosoft.com)" and password have set. I can login by pikpakAPI (https://github.com/Quan666/PikPakAPI)

I chcked the code we use same api url. I need more information about it. You can join my group in the YouTube video to give me more information.

**Comment by ykxVK8yL5L** [comment]
> > > Same problem with email login
> > 
> > 
> > If you are using gmail to login. You need set password in pikpak.
> 
> No, I use microsoft devloper email "[xxxxx@xxx.onmicrosoft.com](mailto:xxxxx@xxx.onmicrosoft.com)" and password have set. I can login by pikpakAPI (https://github.com/Quan666/PikPakAPI)

I suggest you give up this repository. It sucks!!  If there are many file it may crash. And it runs slowly. I even don’t use it myself.
