### ISSUE TITLE
copying big file will end at around 2G is downloaded

### ISSUE THREAD

**Issue by cathy10117** [ykxVK8yL5L/pikpak-fuse#4]
I am copying a file of size 6G from pikpak-fuse mount directory to local directory,and the copy will end at the file has been copy 2062146508 bytes. I try serval times, and it's all the same.

**Comment by ykxVK8yL5L** [comment]
> I am copying a file of size 6G from pikpak-fuse mount directory to local directory,and the copy will end at the file has been copy 2062146508 bytes. I try serval times, and it's all the same.

I don’t suggest you use this to upload file. Use this: https://github.com/52funny/pikpakcli

**Comment by s0trcwd1** [comment]
我从pikpak复制3G文件到本地，再秒传到百度网盘正常，复制4.3G到本地，但文件大小只有370M左右，几次都是这样，也没抱错，也没日志。
我是会员，复制是单个文件。

**Comment by ykxVK8yL5L** [comment]
> 我从pikpak复制3G文件到本地，再秒传到百度网盘正常，复制4.3G到本地，但文件大小只有370M左右，几次都是这样，也没抱错，也没日志。 我是会员，复制是单个文件。

抱歉现在才看到回复，不太清楚你说的什么意思？ 是从pikpak-fuse复制到本地只有370m么？ 如果是我的程序的话打开调试应该有输出，每次大小只有370m？ 会不会是网络问题？ 秒传的话应该是检测文件hash没有真正上传。但是370m，我就不清楚了。我都是下载直链
